=== trentStan/MiniJavaProjects/xml/build/classes/xml/details.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT supplier (name|address|product)*>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (street|city|zip)*>
<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT zip (#PCDATA)>
<!ELEMENT product (type|price|quantity)*>
<!ELEMENT type (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>

=== trentStan/MiniJavaProjects/xml/src/xml/final.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?xml-stylesheet href="layout.css"?>
<!DOCTYPE supplier SYSTEM "details.dtd">
<supplier>
    <name>Test Company</name>
    <address>
        <street>Third Avenue</street>
        <city>Cape Town</city>
        <zip>7080</zip>
    </address>
    <product>
        <type>Laptop</type>
        <price>R5500</price>
        <quantity>7 items</quantity>
    </product>
</supplier>
