=== trentStan/MiniJavaProjects/xml2/build/classes/xml2/menu.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT menu (name, price, description, portionsize)+>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT portionsize (#PCDATA)>

=== trentStan/MiniJavaProjects/xml2/build/classes/xml2/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE menu SYSTEM "menu.dtd">
<menu>

    <name>Pizza</name>
    <price>50</price>
    <description>macon and cheese</description>
    <portionsize>medium-sized pizzas</portionsize>
    
    
</menu>
<menu>
    <name>Gatsby</name>
    <price>55</price>
    <description>chips, polony and steak</description>
    <portionsize>1 foot</portionsize>
</menu>

=== trentStan/MiniJavaProjects/xml2/src/xml2/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?xml-stylesheet href="menu.css"?>
<!DOCTYPE menu SYSTEM "menu.dtd">
<menu>

    <food>
        <name>Pizza</name>
        <price>50</price>
        <description>macon and cheese</description>
        <portionsize>medium-sized pizzas</portionsize>
    </food>
    <food>
        <name>Gatsby</name>
        <price>55</price>
        <description>chips, polony and steak</description>
        <portionsize>1 foot</portionsize>
    </food>
    
    
</menu>
